export const GALLERY_IMAGES = [
  { id: 1, src: "/gallery/gallery-01.jpg", alt: "Ronin Harrisburg venue photo 1", category: "patio" as const, featured: true },
  { id: 2, src: "/gallery/gallery-02.jpg", alt: "Ronin Harrisburg venue photo 2", category: "night" as const, featured: true },
  { id: 3, src: "/gallery/gallery-03.jpg", alt: "Ronin Harrisburg venue photo 3", category: "main-room" as const, featured: true },
  { id: 4, src: "/gallery/gallery-04.jpg", alt: "Ronin Harrisburg venue photo 4", category: "patio" as const, featured: true },
  { id: 5, src: "/gallery/gallery-05.jpg", alt: "Ronin Harrisburg venue photo 5", category: "night" as const, featured: true },
  { id: 6, src: "/gallery/gallery-06.jpg", alt: "Ronin Harrisburg venue photo 6", category: "main-room" as const, featured: true },
  { id: 7, src: "/gallery/gallery-07.jpg", alt: "Ronin Harrisburg venue photo 7", category: "patio" as const, featured: true },
  { id: 8, src: "/gallery/gallery-08.jpg", alt: "Ronin Harrisburg venue photo 8", category: "night" as const, featured: true },
  { id: 9, src: "/gallery/gallery-09.jpg", alt: "Ronin Harrisburg venue photo 9", category: "main-room" as const, featured: false },
  { id: 10, src: "/gallery/gallery-10.jpg", alt: "Ronin Harrisburg venue photo 10", category: "patio" as const, featured: false },
  { id: 11, src: "/gallery/gallery-11.jpg", alt: "Ronin Harrisburg venue photo 11", category: "night" as const, featured: false },
  { id: 12, src: "/gallery/gallery-12.jpg", alt: "Ronin Harrisburg venue photo 12", category: "main-room" as const, featured: false },
  { id: 13, src: "/gallery/gallery-13.jpg", alt: "Ronin Harrisburg venue photo 13", category: "patio" as const, featured: false },
  { id: 14, src: "/gallery/gallery-14.jpg", alt: "Ronin Harrisburg venue photo 14", category: "night" as const, featured: false },
  { id: 15, src: "/gallery/gallery-15.jpg", alt: "Ronin Harrisburg venue photo 15", category: "main-room" as const, featured: false },
  { id: 16, src: "/gallery/gallery-16.jpg", alt: "Ronin Harrisburg venue photo 16", category: "patio" as const, featured: false },
  { id: 17, src: "/gallery/gallery-17.jpg", alt: "Ronin Harrisburg venue photo 17", category: "night" as const, featured: false },
  { id: 18, src: "/gallery/gallery-18.jpg", alt: "Ronin Harrisburg venue photo 18", category: "main-room" as const, featured: false },
  { id: 19, src: "/gallery/gallery-19.jpg", alt: "Ronin Harrisburg venue photo 19", category: "patio" as const, featured: false },
  { id: 20, src: "/gallery/gallery-20.jpg", alt: "Ronin Harrisburg venue photo 20", category: "night" as const, featured: false },
  { id: 21, src: "/gallery/gallery-21.jpg", alt: "Ronin Harrisburg venue photo 21", category: "main-room" as const, featured: false },
  { id: 22, src: "/gallery/gallery-22.jpg", alt: "Ronin Harrisburg venue photo 22", category: "patio" as const, featured: false },
  { id: 23, src: "/gallery/gallery-23.jpg", alt: "Ronin Harrisburg venue photo 23", category: "night" as const, featured: false },
  { id: 24, src: "/gallery/gallery-24.jpg", alt: "Ronin Harrisburg venue photo 24", category: "main-room" as const, featured: false },
  { id: 25, src: "/gallery/gallery-25.jpg", alt: "Ronin Harrisburg venue photo 25", category: "patio" as const, featured: false },
  { id: 26, src: "/gallery/gallery-26.jpg", alt: "Ronin Harrisburg venue photo 26", category: "night" as const, featured: false },
  { id: 27, src: "/gallery/gallery-27.jpg", alt: "Ronin Harrisburg venue photo 27", category: "main-room" as const, featured: false },
  { id: 28, src: "/gallery/gallery-28.jpg", alt: "Ronin Harrisburg venue photo 28", category: "patio" as const, featured: false },
  { id: 29, src: "/gallery/gallery-29.jpg", alt: "Ronin Harrisburg venue photo 29", category: "night" as const, featured: false },
  { id: 30, src: "/gallery/gallery-30.jpg", alt: "Ronin Harrisburg venue photo 30", category: "main-room" as const, featured: false },
  { id: 31, src: "/gallery/gallery-31.jpg", alt: "Ronin Harrisburg venue photo 31", category: "patio" as const, featured: false },
  { id: 32, src: "/gallery/gallery-32.jpg", alt: "Ronin Harrisburg venue photo 32", category: "night" as const, featured: false },
  { id: 33, src: "/gallery/gallery-33.jpg", alt: "Ronin Harrisburg venue photo 33", category: "main-room" as const, featured: false },
  { id: 34, src: "/gallery/gallery-34.jpg", alt: "Ronin Harrisburg venue photo 34", category: "patio" as const, featured: false },
] as const;

export type GalleryImage = (typeof GALLERY_IMAGES)[number];